Traceback (most recent call last):
  File "/home/eegrad/rghosal/cluster_backup/anticipation_Rinki_final/videoblip_orig/main.py", line 165, in <module>
    main()
  File "/home/eegrad/rghosal/cluster_backup/anticipation_Rinki_final/videoblip_orig/main.py", line 93, in main
    train_dataset=SegFileDataset(forecast_annot_tr_dir,no_frame,processor,num_query_tokens=32,decoder_only_lm=True,sample_for_test=False) #clip_path is within forecast_annot_tr_dir
TypeError: SegFileDataset.__init__() got multiple values for argument 'num_query_tokens'
Traceback (most recent call last):
  File "/home/eegrad/rghosal/cluster_backup/anticipation_Rinki_final/videoblip_orig/main.py", line 165, in <module>
    main()
  File "/home/eegrad/rghosal/cluster_backup/anticipation_Rinki_final/videoblip_orig/main.py", line 93, in main
    train_dataset=SegFileDataset(forecast_annot_tr_dir,no_frame,processor,num_query_tokens=32,decoder_only_lm=True,sample_for_test=False) #clip_path is within forecast_annot_tr_dir
TypeError: SegFileDataset.__init__() got multiple values for argument 'num_query_tokens'